// Seed de Profissionais da Educação (equipe completa).
// Marcador: e-mail no domínio "@escola.demo" para remoção segura.

export const SEED_PROFISSIONAL_EMAIL_DOMAIN = "escola.demo";

export type SeedProfissional = {
  nome: string;
  cargo: "diretor" | "coordenador" | "professor" | "secretario" | "outro";
  cargo_descricao?: string;
  email: string;
  telefone?: string;
  formacao?: string;
  bio?: string;
  disciplinas?: string[];
  anos_experiencia?: number;
  ano_ingresso?: number;
  destaque?: boolean;
  ordem?: number;
};

export const SEED_PROFISSIONAIS: SeedProfissional[] = [
  // Diretoria
  {
    nome: "Dra. Beatriz Almeida Rocha",
    cargo: "diretor",
    cargo_descricao: "Diretora Geral",
    email: `seed.diretor.1@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0101",
    formacao: "Doutora em Educação (USP) · Mestre em Gestão Escolar",
    bio: "Lidera a escola há mais de uma década com foco em educação humanizada, inovação pedagógica e excelência acadêmica.",
    anos_experiencia: 22,
    ano_ingresso: 2012,
    destaque: true,
    ordem: 1,
  },
  {
    nome: "Prof. Antônio Carvalho Neto",
    cargo: "diretor",
    cargo_descricao: "Vice-Diretor",
    email: `seed.diretor.2@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0102",
    formacao: "Mestre em Administração Escolar · Licenciado em História",
    bio: "Responsável pela gestão administrativa e relacionamento com famílias.",
    anos_experiencia: 18,
    ano_ingresso: 2015,
    ordem: 2,
  },
  // Coordenação
  {
    nome: "Profa. Camila Ribeiro Souza",
    cargo: "coordenador",
    cargo_descricao: "Coordenadora Pedagógica – Fundamental II",
    email: `seed.coordenador.1@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0201",
    formacao: "Mestre em Educação · Pedagogia (UNESP)",
    bio: "Coordena o trabalho pedagógico do Ensino Fundamental II com foco em metodologias ativas.",
    anos_experiencia: 15,
    ano_ingresso: 2017,
    ordem: 3,
  },
  {
    nome: "Prof. Diego Martins Pereira",
    cargo: "coordenador",
    cargo_descricao: "Coordenador Pedagógico – Ensino Médio",
    email: `seed.coordenador.2@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0202",
    formacao: "Mestre em Matemática Aplicada · Licenciado em Matemática",
    bio: "Acompanha o currículo do Ensino Médio e a preparação para vestibulares e ENEM.",
    anos_experiencia: 16,
    ano_ingresso: 2016,
    ordem: 4,
  },
  // Professores
  {
    nome: "Profa. Ana Beatriz Lima",
    cargo: "professor",
    cargo_descricao: "Professora de Português",
    email: `seed.professor.1@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0301",
    formacao: "Letras (USP) · Especialista em Literatura Brasileira",
    bio: "Apaixonada por literatura e produção textual, conduz projetos de leitura há mais de uma década.",
    disciplinas: ["Português"],
    anos_experiencia: 14,
    ano_ingresso: 2018,
    ordem: 10,
  },
  {
    nome: "Prof. Marcos Vinícius Souza",
    cargo: "professor",
    cargo_descricao: "Professor de Matemática",
    email: `seed.professor.2@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0302",
    formacao: "Licenciatura em Matemática (UNICAMP)",
    bio: "Orientador da equipe da OBMEP, transforma a matemática em desafios cativantes.",
    disciplinas: ["Matemática"],
    anos_experiencia: 12,
    ano_ingresso: 2019,
    ordem: 11,
  },
  {
    nome: "Prof. Eduardo Ramos",
    cargo: "professor",
    cargo_descricao: "Professor de História",
    email: `seed.professor.3@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0303",
    formacao: "Mestre em História Social",
    bio: "Conduz aulas dinâmicas com debates contemporâneos.",
    disciplinas: ["História"],
    anos_experiencia: 13,
    ano_ingresso: 2018,
    ordem: 12,
  },
  {
    nome: "Profa. Cláudia Mendes",
    cargo: "professor",
    cargo_descricao: "Professora de Geografia",
    email: `seed.professor.4@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0304",
    formacao: "Geografia (USP) · Especialista em Geopolítica",
    disciplinas: ["Geografia"],
    anos_experiencia: 11,
    ano_ingresso: 2020,
    ordem: 13,
  },
  {
    nome: "Profa. Patrícia Nogueira",
    cargo: "professor",
    cargo_descricao: "Professora de Ciências",
    email: `seed.professor.5@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0305",
    formacao: "Ciências Biológicas · Pós em Educação Ambiental",
    disciplinas: ["Ciências"],
    anos_experiencia: 10,
    ano_ingresso: 2020,
    ordem: 14,
  },
  {
    nome: "Profa. Helena Carvalho",
    cargo: "professor",
    cargo_descricao: "Professora de Biologia",
    email: `seed.professor.6@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0306",
    formacao: "Mestre em Biologia Molecular (USP)",
    disciplinas: ["Biologia"],
    anos_experiencia: 9,
    ano_ingresso: 2021,
    ordem: 15,
  },
  {
    nome: "Prof. Ricardo Tavares",
    cargo: "professor",
    cargo_descricao: "Professor de Física",
    email: `seed.professor.7@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0307",
    formacao: "Bacharel e Licenciado em Física (USP)",
    disciplinas: ["Física"],
    anos_experiencia: 14,
    ano_ingresso: 2017,
    ordem: 16,
  },
  {
    nome: "Profa. Mariana Alves",
    cargo: "professor",
    cargo_descricao: "Professora de Química",
    email: `seed.professor.8@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0308",
    formacao: "Química (UFSCar) · Especialista em Educação Científica",
    disciplinas: ["Química"],
    anos_experiencia: 12,
    ano_ingresso: 2019,
    ordem: 17,
  },
  {
    nome: "Profa. Juliana Prado",
    cargo: "professor",
    cargo_descricao: "Professora de Inglês",
    email: `seed.professor.9@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0309",
    formacao: "Letras-Inglês · Cambridge CELTA",
    disciplinas: ["Inglês"],
    anos_experiencia: 11,
    ano_ingresso: 2019,
    ordem: 18,
  },
  {
    nome: "Prof. Bruno Henrique",
    cargo: "professor",
    cargo_descricao: "Professor de Educação Física",
    email: `seed.professor.10@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0310",
    formacao: "Educação Física (UNESP) · Treinador de Futsal",
    disciplinas: ["Educação Física"],
    anos_experiencia: 13,
    ano_ingresso: 2018,
    ordem: 19,
  },
  {
    nome: "Profa. Larissa Oliveira",
    cargo: "professor",
    cargo_descricao: "Professora de Artes",
    email: `seed.professor.11@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0311",
    formacao: "Artes Visuais (UNESP)",
    disciplinas: ["Artes"],
    anos_experiencia: 8,
    ano_ingresso: 2021,
    ordem: 20,
  },
  {
    nome: "Prof. Sérgio Martins",
    cargo: "professor",
    cargo_descricao: "Professor de Filosofia",
    email: `seed.professor.12@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0312",
    formacao: "Mestre em Filosofia (USP)",
    disciplinas: ["Filosofia"],
    anos_experiencia: 15,
    ano_ingresso: 2017,
    ordem: 21,
  },
  {
    nome: "Prof. Felipe Andrade",
    cargo: "professor",
    cargo_descricao: "Professor de Sociologia",
    email: `seed.professor.13@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0313",
    formacao: "Ciências Sociais (USP)",
    disciplinas: ["Sociologia"],
    anos_experiencia: 9,
    ano_ingresso: 2021,
    ordem: 22,
  },
  // Secretaria
  {
    nome: "Renata Silva Gomes",
    cargo: "secretario",
    cargo_descricao: "Secretária Escolar",
    email: `seed.secretario.1@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0401",
    formacao: "Administração Escolar",
    bio: "Responsável por matrículas, históricos e documentação acadêmica.",
    anos_experiencia: 12,
    ano_ingresso: 2018,
    ordem: 30,
  },
  {
    nome: "Paulo Henrique Costa",
    cargo: "secretario",
    cargo_descricao: "Assistente de Secretaria",
    email: `seed.secretario.2@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0402",
    formacao: "Técnico em Administração",
    anos_experiencia: 6,
    ano_ingresso: 2022,
    ordem: 31,
  },
  // Demais profissionais
  {
    nome: "Lucia Fernanda Dias",
    cargo: "outro",
    cargo_descricao: "Psicopedagoga",
    email: `seed.outro.1@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0501",
    formacao: "Psicopedagogia Clínica e Institucional",
    bio: "Apoia o desenvolvimento socioemocional e a aprendizagem dos estudantes.",
    anos_experiencia: 10,
    ano_ingresso: 2020,
    ordem: 40,
  },
  {
    nome: "Rafael Moreira",
    cargo: "outro",
    cargo_descricao: "Bibliotecário",
    email: `seed.outro.2@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0502",
    formacao: "Biblioteconomia (USP)",
    anos_experiencia: 7,
    ano_ingresso: 2022,
    ordem: 41,
  },
  {
    nome: "Sandra Mota",
    cargo: "outro",
    cargo_descricao: "Nutricionista",
    email: `seed.outro.3@${SEED_PROFISSIONAL_EMAIL_DOMAIN}`,
    telefone: "(11) 95000-0503",
    formacao: "Nutrição (UNIFESP)",
    anos_experiencia: 9,
    ano_ingresso: 2021,
    ordem: 42,
  },
];
