// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhmdjjbqbbsgcsjujuhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obWRqamJxYmJzZ2NzanVqdWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3Nzg2MDEsImV4cCI6MjA5NjM1NDYwMX0.uFOcywCX5U61t3-o_nNiiGHa_i769X2NHYY82CEL-ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});